<?php
/*
 This file is part of SICEKIT, http://oss.inqnet.at/trac/sicekit.
 SICEKIT CSS Extension
 Copyright (c) 2009 SICEKIT Development Team.
*/

$wgHooks['SkinTemplateSetupPageCss'][] = 'SICEKIT_CSS_HookSkinTemplateSetupPageCss';

function SICEKIT_CSS_GetCssImport($css_page_name, $media = '') {
        global $wgSquidMaxage;
	$query = wfArrayToCGI( array(
		'usemsgcache' => 'yes',
		'ctype' => 'text/css',
		'action' => 'raw',
		'smaxage' => $wgSquidMaxage,
		'maxage' => $wgSquidMaxage,
	));

	$title = Title::makeTitleSafe( NS_MEDIAWIKI, $css_page_name );
	if (!is_object($title))
		return "";
	$url = $title->getLocalURL( $query );
	$import = "@import url(\"$url\") $media;\n";
	return $import;
}

function SICEKIT_CSS_HookSkinTemplateSetupPageCss( &$out ) {
	$out .= "/* Generated by SICEKIT_CSS_HookSkinTemplateSetupPageCss */\n";
	$out .= SICEKIT_CSS_GetCssImport('SICEKIT.css');
	$out .= SICEKIT_CSS_GetCssImport('SICEKIT-print.css', 'print');
	$out .= "/* end */\n";
	return true;
}

